//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTech.Elite.Client.Modules.B3Center.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTech.Elite.Client.Modules.B3Center.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3 Center.
        /// </summary>
        internal static string B3CenterName {
            get {
                return ResourceManager.GetString("B3CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is currently busy, do you really wish to exit?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the user interface.
        ///Reason: {0}.
        /// </summary>
        internal static string CreateUIFailed {
            get {
                return ResourceManager.GetString("CreateUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading reports.
        /// </summary>
        internal static string DownloadingReports {
            get {
                return ResourceManager.GetString("DownloadingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download reports. {0}.
        /// </summary>
        internal static string ErrorDownloadingReports {
            get {
                return ResourceManager.GetString("ErrorDownloadingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date must be before the end date..
        /// </summary>
        internal static string ErrorEndDateOccuresBeforStartDate {
            get {
                return ResourceManager.GetString("ErrorEndDateOccuresBeforStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting card must be before the ending card..
        /// </summary>
        internal static string ErrorEndingCardOccuresBeforeStartingCard {
            get {
                return ResourceManager.GetString("ErrorEndingCardOccuresBeforeStartingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bonus balls must include 1 ball from row B, I, G, O, and 2 balls from row N.
        /// </summary>
        internal static string ErrorEnforceMixBonusBalls {
            get {
                return ResourceManager.GetString("ErrorEnforceMixBonusBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game balls must include 5 balls from row B, I, G, O, and 4 balls from row N.
        /// </summary>
        internal static string ErrorEnforceMixGameBalls {
            get {
                return ResourceManager.GetString("ErrorEnforceMixGameBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load report. {0}.
        /// </summary>
        internal static string ErrorLoadingReport {
            get {
                return ResourceManager.GetString("ErrorLoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print report..
        /// </summary>
        internal static string ErrorPrintingReport {
            get {
                return ResourceManager.GetString("ErrorPrintingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Full Screen.
        /// </summary>
        internal static string ExitFullScreen {
            get {
                return ResourceManager.GetString("ExitFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve B3 settings. {0}.
        /// </summary>
        internal static string GetB3SettingsFailed {
            get {
                return ResourceManager.GetString("GetB3SettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the machine id.
        ///Reason: {0}.
        /// </summary>
        internal static string GetDeviceInfoFailed {
            get {
                return ResourceManager.GetString("GetDeviceInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve this machine&apos;s information from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string GetSettingsFailed {
            get {
                return ResourceManager.GetString("GetSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call speed is invalid..
        /// </summary>
        internal static string InvalidCallSpeed {
            get {
                return ResourceManager.GetString("InvalidCallSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call speed range is invalid..
        /// </summary>
        internal static string InvalidCallSpeedRange {
            get {
                return ResourceManager.GetString("InvalidCallSpeedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum call speed is too invalid..
        /// </summary>
        internal static string InvalidMaxCallSpeed {
            get {
                return ResourceManager.GetString("InvalidMaxCallSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum call speed is invalid..
        /// </summary>
        internal static string InvalidMinCallSpeed {
            get {
                return ResourceManager.GetString("InvalidMinCallSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application controllers..
        /// </summary>
        internal static string LoadingControllers {
            get {
                return ResourceManager.GetString("LoadingControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the application controllers.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadingControllersFailed {
            get {
                return ResourceManager.GetString("LoadingControllersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this machine&apos;s information.
        /// </summary>
        internal static string LoadingMachineInfo {
            get {
                return ResourceManager.GetString("LoadingMachineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resources.
        /// </summary>
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load B3 Center&apos;s resource dictionaries.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadResourceDictionariesFailed {
            get {
                return ResourceManager.GetString("LoadResourceDictionariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the log.
        ///Reason: {0}.
        /// </summary>
        internal static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the user to manage system settings and games for the B3 system..
        /// </summary>
        internal static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameTech Edge Bingo System B3 Center Module.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accounts to void.
        /// </summary>
        internal static string NoOutstandingAccountsToVoidString {
            get {
                return ResourceManager.GetString("NoOutstandingAccountsToVoidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost.
        ///
        ///Shutting down....
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Active Session.
        /// </summary>
        internal static string SesionEndActiveSessionString {
            get {
                return ResourceManager.GetString("SesionEndActiveSessionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Session.
        /// </summary>
        internal static string SesionStartNewSessionString {
            get {
                return ResourceManager.GetString("SesionStartNewSessionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session is currently active..
        /// </summary>
        internal static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to end the session.
        ///Reason: {0}.
        /// </summary>
        internal static string SessionEndFailed {
            get {
                return ResourceManager.GetString("SessionEndFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending session, please wait..
        /// </summary>
        internal static string SessionEndProgress {
            get {
                return ResourceManager.GetString("SessionEndProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended session successfully..
        /// </summary>
        internal static string SessionEndSuccess {
            get {
                return ResourceManager.GetString("SessionEndSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve session information. {0}.
        /// </summary>
        internal static string SessionInfoFailed {
            get {
                return ResourceManager.GetString("SessionInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving session information, please wait..
        /// </summary>
        internal static string SessionInfoProgress {
            get {
                return ResourceManager.GetString("SessionInfoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved session information successfully..
        /// </summary>
        internal static string SessionInfoSuccess {
            get {
                return ResourceManager.GetString("SessionInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update balls while in session..
        /// </summary>
        internal static string SessionInSessionSetBallsDisabled {
            get {
                return ResourceManager.GetString("SessionInSessionSetBallsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve operator information..
        /// </summary>
        internal static string SessionOperatorListFailed {
            get {
                return ResourceManager.GetString("SessionOperatorListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving operator information, please wait..
        /// </summary>
        internal static string SessionOperatorListProgress {
            get {
                return ResourceManager.GetString("SessionOperatorListProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved operator information successfully..
        /// </summary>
        internal static string SessionOperatorListSuccess {
            get {
                return ResourceManager.GetString("SessionOperatorListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set ball list. {0}.
        /// </summary>
        internal static string SessionSetBallsFailed {
            get {
                return ResourceManager.GetString("SessionSetBallsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Balls, please wait.
        /// </summary>
        internal static string SessionSetBallsProgress {
            get {
                return ResourceManager.GetString("SessionSetBallsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is currently active. To start a new session, stop the current session..
        /// </summary>
        internal static string SessionStarted {
            get {
                return ResourceManager.GetString("SessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the session.
        ///Reason: {0}.
        /// </summary>
        internal static string SessionStartFailed {
            get {
                return ResourceManager.GetString("SessionStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting session, please wait..
        /// </summary>
        internal static string SessionStartProgress {
            get {
                return ResourceManager.GetString("SessionStartProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started session successfully..
        /// </summary>
        internal static string SessionStartSuccess {
            get {
                return ResourceManager.GetString("SessionStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=B3-Server;Initial Catalog=Daily;Persist Security Info=True;User ID=sqluser;Password=gly*cine83.
        /// </summary>
        internal static string SQLB3Connection {
            get {
                return ResourceManager.GetString("SQLB3Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=GtiServer;Initial Catalog=Daily;Persist Security Info=True;User ID=sqluser;Password=gly*cine83.
        /// </summary>
        internal static string SQLGtiConnection {
            get {
                return ResourceManager.GetString("SQLGtiConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting B3 Center....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} outstanding accounts.
        ///Would you like to void all outstanding accounts? .
        /// </summary>
        internal static string VoidOutstandingAccountsYesNoString {
            get {
                return ResourceManager.GetString("VoidOutstandingAccountsYesNoString", resourceCulture);
            }
        }
    }
}
